import './globals.css';

export const metadata = {
	title: 'Artiste',
	description: 'Generated by me amor',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
